import { defineConfig } from "@lovable.dev/vite-tanstack-config";
import { VitePWA, type ManifestOptions } from "vite-plugin-pwa";
import { loadEnv, type Plugin, type ResolvedConfig } from "vite";
import fs from "node:fs";
import path from "node:path";

const env = loadEnv("production", process.cwd(), "VITE_");

function injectFcmServiceWorker(loadedEnv: Record<string, string>): Plugin {
  let outDir = "dist";
  return {
    name: "sahl-dz:inject-fcm-sw",
    apply: "build",
    configResolved(config: ResolvedConfig) {
      outDir = config.build.outDir;
    },
    closeBundle() {
      const { VITE_FIREBASE_API_KEY } = loadedEnv;
      const { VITE_FIREBASE_AUTH_DOMAIN } = loadedEnv;
      const { VITE_FIREBASE_PROJECT_ID } = loadedEnv;
      const { VITE_FIREBASE_STORAGE_BUCKET } = loadedEnv;
      const { VITE_FIREBASE_MESSAGING_SENDER_ID } = loadedEnv;
      const { VITE_FIREBASE_APP_ID } = loadedEnv;
      if (
        !VITE_FIREBASE_API_KEY ||
        !VITE_FIREBASE_APP_ID ||
        !VITE_FIREBASE_PROJECT_ID
      ) {
        console.warn(
          "[sahl-dz] VITE_FIREBASE_* missing; skipping firebase-messaging-sw.js (no background push)",
        );
        return;
      }
      const config = JSON.stringify({
        apiKey: VITE_FIREBASE_API_KEY,
        authDomain: VITE_FIREBASE_AUTH_DOMAIN || undefined,
        projectId: VITE_FIREBASE_PROJECT_ID,
        storageBucket: VITE_FIREBASE_STORAGE_BUCKET || undefined,
        messagingSenderId: VITE_FIREBASE_MESSAGING_SENDER_ID || undefined,
        appId: VITE_FIREBASE_APP_ID,
      });
      const content = `// Generated by SahlDZ — do not edit by hand.
importScripts("https://www.gstatic.com/firebasejs/11.7.0/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/11.7.0/firebase-messaging-compat.js");

firebase.initializeApp(${config});

const messaging = firebase.messaging();
`;
      const targets = new Set([outDir, path.resolve(outDir, "..", "client")]);
      for (const dir of targets) {
        const dest = path.resolve(dir, "firebase-messaging-sw.js");
        fs.mkdirSync(path.dirname(dest), { recursive: true });
        fs.writeFileSync(dest, content);
      }
      console.warn(
        "[sahl-dz] wrote firebase-messaging-sw.js for background push",
      );
    },
  };
}

const manifest: Partial<ManifestOptions> & { gcm_sender_id?: string } = {
  name: "SahlDZ - إدارة المطعم",
  short_name: "SahlDZ",
  description: "تطبيق إدارة المطعم - تقارير وإشعارات تحديثات فورية",
  theme_color: "#F59E0B",
  background_color: "#0F172A",
  display: "standalone",
  orientation: "portrait",
  scope: "/",
  start_url: "/mobile",
  gcm_sender_id: env.VITE_FIREBASE_MESSAGING_SENDER_ID || "",
  icons: [
    {
      src: "/icon-192.png",
      sizes: "192x192",
      type: "image/png",
    },
    {
      src: "/icon-512.png",
      sizes: "512x512",
      type: "image/png",
    },
    {
      src: "/icon-512.png",
      sizes: "512x512",
      type: "image/png",
      purpose: "maskable",
    },
  ],
};

const isProductionBuild = process.env.NODE_ENV === "production";

export default defineConfig({
  nitro: isProductionBuild
    ? {
        preset: process.env.NITRO_PRESET || "vercel",
        output: {
          dir: ".vercel/output",
          serverDir: ".vercel/output/functions/__server.func",
          publicDir: ".vercel/output/static",
        },
      }
    : false,
  vite: {
    server: {
      strictPort: true,
      port: 8080,
    },
    plugins: [
      VitePWA({
        registerType: "autoUpdate",
        includeAssets: ["favicon.ico", "robots.txt", "apple-touch-icon.png"],
        manifest,
        workbox: {
          globPatterns: ["**/*.{js,css,html,ico,png,svg,woff2}"],
          runtimeCaching: [
            {
              urlPattern: /^https:\/\/api\.telegram\.org\/.*/i,
              handler: "NetworkFirst",
              options: {
                cacheName: "telegram-api",
                expiration: { maxEntries: 10, maxAgeSeconds: 300 },
              },
            },
          ],
        },
      }),
      injectFcmServiceWorker(env),
    ],
  },
});
