/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as CashierRouteImport } from './routes/cashier'
import { Route as CashierLoginRouteImport } from './routes/cashier-login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as KitchenLoginRouteImport } from './routes/kitchen-login'
import { Route as KitchenScreenRouteImport } from './routes/kitchen-screen'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StaffLoginRouteImport } from './routes/staff-login'
import { Route as WaiterLoginRouteImport } from './routes/waiter-login'
import { Route as WaiterScreenRouteImport } from './routes/waiter-screen'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountSettingsRouteImport } from './routes/account.settings'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardDownloadRouteImport } from './routes/dashboard.download'
import { Route as DashboardMenuRouteImport } from './routes/dashboard.menu'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard.reviews'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardTablesRouteImport } from './routes/dashboard.tables'
import { Route as InternalManagersRouteImport } from './routes/internal.managers'
import { Route as MobileIndexRouteImport } from './routes/mobile.index'
import { Route as MobileDailySummaryRouteImport } from './routes/mobile.daily-summary'
import { Route as MobileInventoryRouteImport } from './routes/mobile.inventory'
import { Route as MobileLoginRouteImport } from './routes/mobile.login'
import { Route as MobileNotificationsRouteImport } from './routes/mobile.notifications'
import { Route as MobileReportsRouteImport } from './routes/mobile.reports'
import { Route as MobileSettingsRouteImport } from './routes/mobile.settings'
import { Route as MobileWeeklyReportRouteImport } from './routes/mobile.weekly-report'
import { Route as OpsIndexRouteImport } from './routes/ops.index'
import { Route as OpsAccountingRouteImport } from './routes/ops.accounting'
import { Route as OpsComplaintsRouteImport } from './routes/ops.complaints'
import { Route as OpsEmployeesRouteImport } from './routes/ops.employees'
import { Route as OpsExpensesRouteImport } from './routes/ops.expenses'
import { Route as OpsInventoryRouteImport } from './routes/ops.inventory'
import { Route as OpsInventoryCountRouteImport } from './routes/ops.inventory-count'
import { Route as OpsMenuRouteImport } from './routes/ops.menu'
import { Route as OpsRecipesRouteImport } from './routes/ops.recipes'
import { Route as OpsReportArchiveRouteImport } from './routes/ops.report-archive'
import { Route as OpsReportsRouteImport } from './routes/ops.reports'
import { Route as OpsStaffPerformanceRouteImport } from './routes/ops.staff-performance'
import { Route as OpsSuppliersRouteImport } from './routes/ops.suppliers'
import { Route as OpsWasteRouteImport } from './routes/ops.waste'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as TTokenRouteImport } from './routes/t.$token'
import { Route as AccountSettingsIndexRouteImport } from './routes/account.settings.index'
import { Route as AccountSettingsAppearanceRouteImport } from './routes/account.settings.appearance'
import { Route as AccountSettingsDeliveryRouteImport } from './routes/account.settings.delivery'
import { Route as AccountSettingsEmployeesRouteImport } from './routes/account.settings.employees'
import { Route as AccountSettingsRestaurantRouteImport } from './routes/account.settings.restaurant'
import { Route as AccountSettingsTakeawayRouteImport } from './routes/account.settings.takeaway'
import { Route as AccountSettingsWelcomeRouteImport } from './routes/account.settings.welcome'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard.settings.index'
import { Route as DashboardSettingsAppearanceRouteImport } from './routes/dashboard.settings.appearance'
import { Route as DashboardSettingsDeliveryRouteImport } from './routes/dashboard.settings.delivery'
import { Route as DashboardSettingsEmployeesRouteImport } from './routes/dashboard.settings.employees'
import { Route as DashboardSettingsRestaurantRouteImport } from './routes/dashboard.settings.restaurant'
import { Route as DashboardSettingsTakeawayRouteImport } from './routes/dashboard.settings.takeaway'
import { Route as DashboardSettingsWelcomeRouteImport } from './routes/dashboard.settings.welcome'
import { Route as OpsEmployeesIndexRouteImport } from './routes/ops.employees.index'
import { Route as OpsEmployeesEmployeeIdRouteImport } from './routes/ops.employees.$employeeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierRoute = CashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierLoginRoute = CashierLoginRouteImport.update({
  id: '/cashier-login',
  path: '/cashier-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenLoginRoute = KitchenLoginRouteImport.update({
  id: '/kitchen-login',
  path: '/kitchen-login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenScreenRoute = KitchenScreenRouteImport.update({
  id: '/kitchen-screen',
  path: '/kitchen-screen',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff-login',
  path: '/staff-login',
  getParentRoute: () => rootRouteImport,
} as any)
const WaiterLoginRoute = WaiterLoginRouteImport.update({
  id: '/waiter-login',
  path: '/waiter-login',
  getParentRoute: () => rootRouteImport,
} as any)
const WaiterScreenRoute = WaiterScreenRouteImport.update({
  id: '/waiter-screen',
  path: '/waiter-screen',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDownloadRoute = DashboardDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMenuRoute = DashboardMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTablesRoute = DashboardTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => DashboardRoute,
} as any)
const InternalManagersRoute = InternalManagersRouteImport.update({
  id: '/internal/managers',
  path: '/internal/managers',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileIndexRoute = MobileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MobileRoute,
} as any)
const MobileDailySummaryRoute = MobileDailySummaryRouteImport.update({
  id: '/daily-summary',
  path: '/daily-summary',
  getParentRoute: () => MobileRoute,
} as any)
const MobileInventoryRoute = MobileInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => MobileRoute,
} as any)
const MobileLoginRoute = MobileLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MobileRoute,
} as any)
const MobileNotificationsRoute = MobileNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MobileRoute,
} as any)
const MobileReportsRoute = MobileReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => MobileRoute,
} as any)
const MobileSettingsRoute = MobileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MobileRoute,
} as any)
const MobileWeeklyReportRoute = MobileWeeklyReportRouteImport.update({
  id: '/weekly-report',
  path: '/weekly-report',
  getParentRoute: () => MobileRoute,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsAccountingRoute = OpsAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => OpsRoute,
} as any)
const OpsComplaintsRoute = OpsComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => OpsRoute,
} as any)
const OpsEmployeesRoute = OpsEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => OpsRoute,
} as any)
const OpsExpensesRoute = OpsExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => OpsRoute,
} as any)
const OpsInventoryRoute = OpsInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => OpsRoute,
} as any)
const OpsInventoryCountRoute = OpsInventoryCountRouteImport.update({
  id: '/inventory-count',
  path: '/inventory-count',
  getParentRoute: () => OpsRoute,
} as any)
const OpsMenuRoute = OpsMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => OpsRoute,
} as any)
const OpsRecipesRoute = OpsRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => OpsRoute,
} as any)
const OpsReportArchiveRoute = OpsReportArchiveRouteImport.update({
  id: '/report-archive',
  path: '/report-archive',
  getParentRoute: () => OpsRoute,
} as any)
const OpsReportsRoute = OpsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OpsRoute,
} as any)
const OpsStaffPerformanceRoute = OpsStaffPerformanceRouteImport.update({
  id: '/staff-performance',
  path: '/staff-performance',
  getParentRoute: () => OpsRoute,
} as any)
const OpsSuppliersRoute = OpsSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => OpsRoute,
} as any)
const OpsWasteRoute = OpsWasteRouteImport.update({
  id: '/waste',
  path: '/waste',
  getParentRoute: () => OpsRoute,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TTokenRoute = TTokenRouteImport.update({
  id: '/t/$token',
  path: '/t/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsIndexRoute = AccountSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountSettingsRoute,
} as any)
const AccountSettingsAppearanceRoute =
  AccountSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AccountSettingsRoute,
  } as any)
const AccountSettingsDeliveryRoute = AccountSettingsDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AccountSettingsRoute,
} as any)
const AccountSettingsEmployeesRoute =
  AccountSettingsEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AccountSettingsRoute,
  } as any)
const AccountSettingsRestaurantRoute =
  AccountSettingsRestaurantRouteImport.update({
    id: '/restaurant',
    path: '/restaurant',
    getParentRoute: () => AccountSettingsRoute,
  } as any)
const AccountSettingsTakeawayRoute = AccountSettingsTakeawayRouteImport.update({
  id: '/takeaway',
  path: '/takeaway',
  getParentRoute: () => AccountSettingsRoute,
} as any)
const AccountSettingsWelcomeRoute = AccountSettingsWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AccountSettingsRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSettingsAppearanceRoute =
  DashboardSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsDeliveryRoute =
  DashboardSettingsDeliveryRouteImport.update({
    id: '/delivery',
    path: '/delivery',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsEmployeesRoute =
  DashboardSettingsEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsRestaurantRoute =
  DashboardSettingsRestaurantRouteImport.update({
    id: '/restaurant',
    path: '/restaurant',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsTakeawayRoute =
  DashboardSettingsTakeawayRouteImport.update({
    id: '/takeaway',
    path: '/takeaway',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsWelcomeRoute =
  DashboardSettingsWelcomeRouteImport.update({
    id: '/welcome',
    path: '/welcome',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const OpsEmployeesIndexRoute = OpsEmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsEmployeesRoute,
} as any)
const OpsEmployeesEmployeeIdRoute = OpsEmployeesEmployeeIdRouteImport.update({
  id: '/$employeeId',
  path: '/$employeeId',
  getParentRoute: () => OpsEmployeesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/cashier': typeof CashierRoute
  '/cashier-login': typeof CashierLoginRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kitchen-login': typeof KitchenLoginRoute
  '/kitchen-screen': typeof KitchenScreenRoute
  '/login': typeof LoginRoute
  '/mobile': typeof MobileRouteWithChildren
  '/ops': typeof OpsRouteWithChildren
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/staff-login': typeof StaffLoginRoute
  '/waiter-login': typeof WaiterLoginRoute
  '/waiter-screen': typeof WaiterScreenRoute
  '/account/settings': typeof AccountSettingsRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/download': typeof DashboardDownloadRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/tables': typeof DashboardTablesRoute
  '/internal/managers': typeof InternalManagersRoute
  '/mobile/daily-summary': typeof MobileDailySummaryRoute
  '/mobile/inventory': typeof MobileInventoryRoute
  '/mobile/login': typeof MobileLoginRoute
  '/mobile/notifications': typeof MobileNotificationsRoute
  '/mobile/reports': typeof MobileReportsRoute
  '/mobile/settings': typeof MobileSettingsRoute
  '/mobile/weekly-report': typeof MobileWeeklyReportRoute
  '/ops/accounting': typeof OpsAccountingRoute
  '/ops/complaints': typeof OpsComplaintsRoute
  '/ops/employees': typeof OpsEmployeesRouteWithChildren
  '/ops/expenses': typeof OpsExpensesRoute
  '/ops/inventory': typeof OpsInventoryRoute
  '/ops/inventory-count': typeof OpsInventoryCountRoute
  '/ops/menu': typeof OpsMenuRoute
  '/ops/recipes': typeof OpsRecipesRoute
  '/ops/report-archive': typeof OpsReportArchiveRoute
  '/ops/reports': typeof OpsReportsRoute
  '/ops/staff-performance': typeof OpsStaffPerformanceRoute
  '/ops/suppliers': typeof OpsSuppliersRoute
  '/ops/waste': typeof OpsWasteRoute
  '/r/$token': typeof RTokenRoute
  '/t/$token': typeof TTokenRoute
  '/account/': typeof AccountIndexRoute
  '/mobile/': typeof MobileIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/account/settings/appearance': typeof AccountSettingsAppearanceRoute
  '/account/settings/delivery': typeof AccountSettingsDeliveryRoute
  '/account/settings/employees': typeof AccountSettingsEmployeesRoute
  '/account/settings/restaurant': typeof AccountSettingsRestaurantRoute
  '/account/settings/takeaway': typeof AccountSettingsTakeawayRoute
  '/account/settings/welcome': typeof AccountSettingsWelcomeRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/dashboard/settings/delivery': typeof DashboardSettingsDeliveryRoute
  '/dashboard/settings/employees': typeof DashboardSettingsEmployeesRoute
  '/dashboard/settings/restaurant': typeof DashboardSettingsRestaurantRoute
  '/dashboard/settings/takeaway': typeof DashboardSettingsTakeawayRoute
  '/dashboard/settings/welcome': typeof DashboardSettingsWelcomeRoute
  '/ops/employees/$employeeId': typeof OpsEmployeesEmployeeIdRoute
  '/account/settings/': typeof AccountSettingsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/ops/employees/': typeof OpsEmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/cashier': typeof CashierRoute
  '/cashier-login': typeof CashierLoginRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kitchen-login': typeof KitchenLoginRoute
  '/kitchen-screen': typeof KitchenScreenRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/staff-login': typeof StaffLoginRoute
  '/waiter-login': typeof WaiterLoginRoute
  '/waiter-screen': typeof WaiterScreenRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/download': typeof DashboardDownloadRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/tables': typeof DashboardTablesRoute
  '/internal/managers': typeof InternalManagersRoute
  '/mobile/daily-summary': typeof MobileDailySummaryRoute
  '/mobile/inventory': typeof MobileInventoryRoute
  '/mobile/login': typeof MobileLoginRoute
  '/mobile/notifications': typeof MobileNotificationsRoute
  '/mobile/reports': typeof MobileReportsRoute
  '/mobile/settings': typeof MobileSettingsRoute
  '/mobile/weekly-report': typeof MobileWeeklyReportRoute
  '/ops/accounting': typeof OpsAccountingRoute
  '/ops/complaints': typeof OpsComplaintsRoute
  '/ops/expenses': typeof OpsExpensesRoute
  '/ops/inventory': typeof OpsInventoryRoute
  '/ops/inventory-count': typeof OpsInventoryCountRoute
  '/ops/menu': typeof OpsMenuRoute
  '/ops/recipes': typeof OpsRecipesRoute
  '/ops/report-archive': typeof OpsReportArchiveRoute
  '/ops/reports': typeof OpsReportsRoute
  '/ops/staff-performance': typeof OpsStaffPerformanceRoute
  '/ops/suppliers': typeof OpsSuppliersRoute
  '/ops/waste': typeof OpsWasteRoute
  '/r/$token': typeof RTokenRoute
  '/t/$token': typeof TTokenRoute
  '/account': typeof AccountIndexRoute
  '/mobile': typeof MobileIndexRoute
  '/ops': typeof OpsIndexRoute
  '/account/settings/appearance': typeof AccountSettingsAppearanceRoute
  '/account/settings/delivery': typeof AccountSettingsDeliveryRoute
  '/account/settings/employees': typeof AccountSettingsEmployeesRoute
  '/account/settings/restaurant': typeof AccountSettingsRestaurantRoute
  '/account/settings/takeaway': typeof AccountSettingsTakeawayRoute
  '/account/settings/welcome': typeof AccountSettingsWelcomeRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/dashboard/settings/delivery': typeof DashboardSettingsDeliveryRoute
  '/dashboard/settings/employees': typeof DashboardSettingsEmployeesRoute
  '/dashboard/settings/restaurant': typeof DashboardSettingsRestaurantRoute
  '/dashboard/settings/takeaway': typeof DashboardSettingsTakeawayRoute
  '/dashboard/settings/welcome': typeof DashboardSettingsWelcomeRoute
  '/ops/employees/$employeeId': typeof OpsEmployeesEmployeeIdRoute
  '/account/settings': typeof AccountSettingsIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/ops/employees': typeof OpsEmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/cashier': typeof CashierRoute
  '/cashier-login': typeof CashierLoginRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kitchen-login': typeof KitchenLoginRoute
  '/kitchen-screen': typeof KitchenScreenRoute
  '/login': typeof LoginRoute
  '/mobile': typeof MobileRouteWithChildren
  '/ops': typeof OpsRouteWithChildren
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/staff-login': typeof StaffLoginRoute
  '/waiter-login': typeof WaiterLoginRoute
  '/waiter-screen': typeof WaiterScreenRoute
  '/account/settings': typeof AccountSettingsRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/download': typeof DashboardDownloadRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/tables': typeof DashboardTablesRoute
  '/internal/managers': typeof InternalManagersRoute
  '/mobile/daily-summary': typeof MobileDailySummaryRoute
  '/mobile/inventory': typeof MobileInventoryRoute
  '/mobile/login': typeof MobileLoginRoute
  '/mobile/notifications': typeof MobileNotificationsRoute
  '/mobile/reports': typeof MobileReportsRoute
  '/mobile/settings': typeof MobileSettingsRoute
  '/mobile/weekly-report': typeof MobileWeeklyReportRoute
  '/ops/accounting': typeof OpsAccountingRoute
  '/ops/complaints': typeof OpsComplaintsRoute
  '/ops/employees': typeof OpsEmployeesRouteWithChildren
  '/ops/expenses': typeof OpsExpensesRoute
  '/ops/inventory': typeof OpsInventoryRoute
  '/ops/inventory-count': typeof OpsInventoryCountRoute
  '/ops/menu': typeof OpsMenuRoute
  '/ops/recipes': typeof OpsRecipesRoute
  '/ops/report-archive': typeof OpsReportArchiveRoute
  '/ops/reports': typeof OpsReportsRoute
  '/ops/staff-performance': typeof OpsStaffPerformanceRoute
  '/ops/suppliers': typeof OpsSuppliersRoute
  '/ops/waste': typeof OpsWasteRoute
  '/r/$token': typeof RTokenRoute
  '/t/$token': typeof TTokenRoute
  '/account/': typeof AccountIndexRoute
  '/mobile/': typeof MobileIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/account/settings/appearance': typeof AccountSettingsAppearanceRoute
  '/account/settings/delivery': typeof AccountSettingsDeliveryRoute
  '/account/settings/employees': typeof AccountSettingsEmployeesRoute
  '/account/settings/restaurant': typeof AccountSettingsRestaurantRoute
  '/account/settings/takeaway': typeof AccountSettingsTakeawayRoute
  '/account/settings/welcome': typeof AccountSettingsWelcomeRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/dashboard/settings/delivery': typeof DashboardSettingsDeliveryRoute
  '/dashboard/settings/employees': typeof DashboardSettingsEmployeesRoute
  '/dashboard/settings/restaurant': typeof DashboardSettingsRestaurantRoute
  '/dashboard/settings/takeaway': typeof DashboardSettingsTakeawayRoute
  '/dashboard/settings/welcome': typeof DashboardSettingsWelcomeRoute
  '/ops/employees/$employeeId': typeof OpsEmployeesEmployeeIdRoute
  '/account/settings/': typeof AccountSettingsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/ops/employees/': typeof OpsEmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/cashier'
    | '/cashier-login'
    | '/dashboard'
    | '/download'
    | '/forgot-password'
    | '/kitchen-login'
    | '/kitchen-screen'
    | '/login'
    | '/mobile'
    | '/ops'
    | '/setup'
    | '/signup'
    | '/staff-login'
    | '/waiter-login'
    | '/waiter-screen'
    | '/account/settings'
    | '/dashboard/analytics'
    | '/dashboard/download'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/tables'
    | '/internal/managers'
    | '/mobile/daily-summary'
    | '/mobile/inventory'
    | '/mobile/login'
    | '/mobile/notifications'
    | '/mobile/reports'
    | '/mobile/settings'
    | '/mobile/weekly-report'
    | '/ops/accounting'
    | '/ops/complaints'
    | '/ops/employees'
    | '/ops/expenses'
    | '/ops/inventory'
    | '/ops/inventory-count'
    | '/ops/menu'
    | '/ops/recipes'
    | '/ops/report-archive'
    | '/ops/reports'
    | '/ops/staff-performance'
    | '/ops/suppliers'
    | '/ops/waste'
    | '/r/$token'
    | '/t/$token'
    | '/account/'
    | '/mobile/'
    | '/ops/'
    | '/account/settings/appearance'
    | '/account/settings/delivery'
    | '/account/settings/employees'
    | '/account/settings/restaurant'
    | '/account/settings/takeaway'
    | '/account/settings/welcome'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/delivery'
    | '/dashboard/settings/employees'
    | '/dashboard/settings/restaurant'
    | '/dashboard/settings/takeaway'
    | '/dashboard/settings/welcome'
    | '/ops/employees/$employeeId'
    | '/account/settings/'
    | '/dashboard/settings/'
    | '/ops/employees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/cashier'
    | '/cashier-login'
    | '/dashboard'
    | '/download'
    | '/forgot-password'
    | '/kitchen-login'
    | '/kitchen-screen'
    | '/login'
    | '/setup'
    | '/signup'
    | '/staff-login'
    | '/waiter-login'
    | '/waiter-screen'
    | '/dashboard/analytics'
    | '/dashboard/download'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/reviews'
    | '/dashboard/tables'
    | '/internal/managers'
    | '/mobile/daily-summary'
    | '/mobile/inventory'
    | '/mobile/login'
    | '/mobile/notifications'
    | '/mobile/reports'
    | '/mobile/settings'
    | '/mobile/weekly-report'
    | '/ops/accounting'
    | '/ops/complaints'
    | '/ops/expenses'
    | '/ops/inventory'
    | '/ops/inventory-count'
    | '/ops/menu'
    | '/ops/recipes'
    | '/ops/report-archive'
    | '/ops/reports'
    | '/ops/staff-performance'
    | '/ops/suppliers'
    | '/ops/waste'
    | '/r/$token'
    | '/t/$token'
    | '/account'
    | '/mobile'
    | '/ops'
    | '/account/settings/appearance'
    | '/account/settings/delivery'
    | '/account/settings/employees'
    | '/account/settings/restaurant'
    | '/account/settings/takeaway'
    | '/account/settings/welcome'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/delivery'
    | '/dashboard/settings/employees'
    | '/dashboard/settings/restaurant'
    | '/dashboard/settings/takeaway'
    | '/dashboard/settings/welcome'
    | '/ops/employees/$employeeId'
    | '/account/settings'
    | '/dashboard/settings'
    | '/ops/employees'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/cashier'
    | '/cashier-login'
    | '/dashboard'
    | '/download'
    | '/forgot-password'
    | '/kitchen-login'
    | '/kitchen-screen'
    | '/login'
    | '/mobile'
    | '/ops'
    | '/setup'
    | '/signup'
    | '/staff-login'
    | '/waiter-login'
    | '/waiter-screen'
    | '/account/settings'
    | '/dashboard/analytics'
    | '/dashboard/download'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/tables'
    | '/internal/managers'
    | '/mobile/daily-summary'
    | '/mobile/inventory'
    | '/mobile/login'
    | '/mobile/notifications'
    | '/mobile/reports'
    | '/mobile/settings'
    | '/mobile/weekly-report'
    | '/ops/accounting'
    | '/ops/complaints'
    | '/ops/employees'
    | '/ops/expenses'
    | '/ops/inventory'
    | '/ops/inventory-count'
    | '/ops/menu'
    | '/ops/recipes'
    | '/ops/report-archive'
    | '/ops/reports'
    | '/ops/staff-performance'
    | '/ops/suppliers'
    | '/ops/waste'
    | '/r/$token'
    | '/t/$token'
    | '/account/'
    | '/mobile/'
    | '/ops/'
    | '/account/settings/appearance'
    | '/account/settings/delivery'
    | '/account/settings/employees'
    | '/account/settings/restaurant'
    | '/account/settings/takeaway'
    | '/account/settings/welcome'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/delivery'
    | '/dashboard/settings/employees'
    | '/dashboard/settings/restaurant'
    | '/dashboard/settings/takeaway'
    | '/dashboard/settings/welcome'
    | '/ops/employees/$employeeId'
    | '/account/settings/'
    | '/dashboard/settings/'
    | '/ops/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  CashierRoute: typeof CashierRoute
  CashierLoginRoute: typeof CashierLoginRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  KitchenLoginRoute: typeof KitchenLoginRoute
  KitchenScreenRoute: typeof KitchenScreenRoute
  LoginRoute: typeof LoginRoute
  MobileRoute: typeof MobileRouteWithChildren
  OpsRoute: typeof OpsRouteWithChildren
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  StaffLoginRoute: typeof StaffLoginRoute
  WaiterLoginRoute: typeof WaiterLoginRoute
  WaiterScreenRoute: typeof WaiterScreenRoute
  AccountSettingsRoute: typeof AccountSettingsRouteWithChildren
  InternalManagersRoute: typeof InternalManagersRoute
  RTokenRoute: typeof RTokenRoute
  TTokenRoute: typeof TTokenRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashier': {
      id: '/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof CashierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashier-login': {
      id: '/cashier-login'
      path: '/cashier-login'
      fullPath: '/cashier-login'
      preLoaderRoute: typeof CashierLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-login': {
      id: '/kitchen-login'
      path: '/kitchen-login'
      fullPath: '/kitchen-login'
      preLoaderRoute: typeof KitchenLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-screen': {
      id: '/kitchen-screen'
      path: '/kitchen-screen'
      fullPath: '/kitchen-screen'
      preLoaderRoute: typeof KitchenScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-login': {
      id: '/staff-login'
      path: '/staff-login'
      fullPath: '/staff-login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiter-login': {
      id: '/waiter-login'
      path: '/waiter-login'
      fullPath: '/waiter-login'
      preLoaderRoute: typeof WaiterLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiter-screen': {
      id: '/waiter-screen'
      path: '/waiter-screen'
      fullPath: '/waiter-screen'
      preLoaderRoute: typeof WaiterScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/download': {
      id: '/dashboard/download'
      path: '/download'
      fullPath: '/dashboard/download'
      preLoaderRoute: typeof DashboardDownloadRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/menu': {
      id: '/dashboard/menu'
      path: '/menu'
      fullPath: '/dashboard/menu'
      preLoaderRoute: typeof DashboardMenuRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tables': {
      id: '/dashboard/tables'
      path: '/tables'
      fullPath: '/dashboard/tables'
      preLoaderRoute: typeof DashboardTablesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/internal/managers': {
      id: '/internal/managers'
      path: '/internal/managers'
      fullPath: '/internal/managers'
      preLoaderRoute: typeof InternalManagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/': {
      id: '/mobile/'
      path: '/'
      fullPath: '/mobile/'
      preLoaderRoute: typeof MobileIndexRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/daily-summary': {
      id: '/mobile/daily-summary'
      path: '/daily-summary'
      fullPath: '/mobile/daily-summary'
      preLoaderRoute: typeof MobileDailySummaryRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/inventory': {
      id: '/mobile/inventory'
      path: '/inventory'
      fullPath: '/mobile/inventory'
      preLoaderRoute: typeof MobileInventoryRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/login': {
      id: '/mobile/login'
      path: '/login'
      fullPath: '/mobile/login'
      preLoaderRoute: typeof MobileLoginRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/notifications': {
      id: '/mobile/notifications'
      path: '/notifications'
      fullPath: '/mobile/notifications'
      preLoaderRoute: typeof MobileNotificationsRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/reports': {
      id: '/mobile/reports'
      path: '/reports'
      fullPath: '/mobile/reports'
      preLoaderRoute: typeof MobileReportsRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/settings': {
      id: '/mobile/settings'
      path: '/settings'
      fullPath: '/mobile/settings'
      preLoaderRoute: typeof MobileSettingsRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/weekly-report': {
      id: '/mobile/weekly-report'
      path: '/weekly-report'
      fullPath: '/mobile/weekly-report'
      preLoaderRoute: typeof MobileWeeklyReportRouteImport
      parentRoute: typeof MobileRoute
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/accounting': {
      id: '/ops/accounting'
      path: '/accounting'
      fullPath: '/ops/accounting'
      preLoaderRoute: typeof OpsAccountingRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/complaints': {
      id: '/ops/complaints'
      path: '/complaints'
      fullPath: '/ops/complaints'
      preLoaderRoute: typeof OpsComplaintsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/employees': {
      id: '/ops/employees'
      path: '/employees'
      fullPath: '/ops/employees'
      preLoaderRoute: typeof OpsEmployeesRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/expenses': {
      id: '/ops/expenses'
      path: '/expenses'
      fullPath: '/ops/expenses'
      preLoaderRoute: typeof OpsExpensesRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/inventory': {
      id: '/ops/inventory'
      path: '/inventory'
      fullPath: '/ops/inventory'
      preLoaderRoute: typeof OpsInventoryRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/inventory-count': {
      id: '/ops/inventory-count'
      path: '/inventory-count'
      fullPath: '/ops/inventory-count'
      preLoaderRoute: typeof OpsInventoryCountRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/menu': {
      id: '/ops/menu'
      path: '/menu'
      fullPath: '/ops/menu'
      preLoaderRoute: typeof OpsMenuRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/recipes': {
      id: '/ops/recipes'
      path: '/recipes'
      fullPath: '/ops/recipes'
      preLoaderRoute: typeof OpsRecipesRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/report-archive': {
      id: '/ops/report-archive'
      path: '/report-archive'
      fullPath: '/ops/report-archive'
      preLoaderRoute: typeof OpsReportArchiveRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/reports': {
      id: '/ops/reports'
      path: '/reports'
      fullPath: '/ops/reports'
      preLoaderRoute: typeof OpsReportsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/staff-performance': {
      id: '/ops/staff-performance'
      path: '/staff-performance'
      fullPath: '/ops/staff-performance'
      preLoaderRoute: typeof OpsStaffPerformanceRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/suppliers': {
      id: '/ops/suppliers'
      path: '/suppliers'
      fullPath: '/ops/suppliers'
      preLoaderRoute: typeof OpsSuppliersRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/waste': {
      id: '/ops/waste'
      path: '/waste'
      fullPath: '/ops/waste'
      preLoaderRoute: typeof OpsWasteRouteImport
      parentRoute: typeof OpsRoute
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$token': {
      id: '/t/$token'
      path: '/t/$token'
      fullPath: '/t/$token'
      preLoaderRoute: typeof TTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings/': {
      id: '/account/settings/'
      path: '/'
      fullPath: '/account/settings/'
      preLoaderRoute: typeof AccountSettingsIndexRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/account/settings/appearance': {
      id: '/account/settings/appearance'
      path: '/appearance'
      fullPath: '/account/settings/appearance'
      preLoaderRoute: typeof AccountSettingsAppearanceRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/account/settings/delivery': {
      id: '/account/settings/delivery'
      path: '/delivery'
      fullPath: '/account/settings/delivery'
      preLoaderRoute: typeof AccountSettingsDeliveryRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/account/settings/employees': {
      id: '/account/settings/employees'
      path: '/employees'
      fullPath: '/account/settings/employees'
      preLoaderRoute: typeof AccountSettingsEmployeesRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/account/settings/restaurant': {
      id: '/account/settings/restaurant'
      path: '/restaurant'
      fullPath: '/account/settings/restaurant'
      preLoaderRoute: typeof AccountSettingsRestaurantRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/account/settings/takeaway': {
      id: '/account/settings/takeaway'
      path: '/takeaway'
      fullPath: '/account/settings/takeaway'
      preLoaderRoute: typeof AccountSettingsTakeawayRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/account/settings/welcome': {
      id: '/account/settings/welcome'
      path: '/welcome'
      fullPath: '/account/settings/welcome'
      preLoaderRoute: typeof AccountSettingsWelcomeRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/appearance': {
      id: '/dashboard/settings/appearance'
      path: '/appearance'
      fullPath: '/dashboard/settings/appearance'
      preLoaderRoute: typeof DashboardSettingsAppearanceRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/delivery': {
      id: '/dashboard/settings/delivery'
      path: '/delivery'
      fullPath: '/dashboard/settings/delivery'
      preLoaderRoute: typeof DashboardSettingsDeliveryRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/employees': {
      id: '/dashboard/settings/employees'
      path: '/employees'
      fullPath: '/dashboard/settings/employees'
      preLoaderRoute: typeof DashboardSettingsEmployeesRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/restaurant': {
      id: '/dashboard/settings/restaurant'
      path: '/restaurant'
      fullPath: '/dashboard/settings/restaurant'
      preLoaderRoute: typeof DashboardSettingsRestaurantRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/takeaway': {
      id: '/dashboard/settings/takeaway'
      path: '/takeaway'
      fullPath: '/dashboard/settings/takeaway'
      preLoaderRoute: typeof DashboardSettingsTakeawayRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/welcome': {
      id: '/dashboard/settings/welcome'
      path: '/welcome'
      fullPath: '/dashboard/settings/welcome'
      preLoaderRoute: typeof DashboardSettingsWelcomeRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/ops/employees/': {
      id: '/ops/employees/'
      path: '/'
      fullPath: '/ops/employees/'
      preLoaderRoute: typeof OpsEmployeesIndexRouteImport
      parentRoute: typeof OpsEmployeesRoute
    }
    '/ops/employees/$employeeId': {
      id: '/ops/employees/$employeeId'
      path: '/$employeeId'
      fullPath: '/ops/employees/$employeeId'
      preLoaderRoute: typeof OpsEmployeesEmployeeIdRouteImport
      parentRoute: typeof OpsEmployeesRoute
    }
  }
}

interface DashboardSettingsRouteChildren {
  DashboardSettingsAppearanceRoute: typeof DashboardSettingsAppearanceRoute
  DashboardSettingsDeliveryRoute: typeof DashboardSettingsDeliveryRoute
  DashboardSettingsEmployeesRoute: typeof DashboardSettingsEmployeesRoute
  DashboardSettingsRestaurantRoute: typeof DashboardSettingsRestaurantRoute
  DashboardSettingsTakeawayRoute: typeof DashboardSettingsTakeawayRoute
  DashboardSettingsWelcomeRoute: typeof DashboardSettingsWelcomeRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsAppearanceRoute: DashboardSettingsAppearanceRoute,
  DashboardSettingsDeliveryRoute: DashboardSettingsDeliveryRoute,
  DashboardSettingsEmployeesRoute: DashboardSettingsEmployeesRoute,
  DashboardSettingsRestaurantRoute: DashboardSettingsRestaurantRoute,
  DashboardSettingsTakeawayRoute: DashboardSettingsTakeawayRoute,
  DashboardSettingsWelcomeRoute: DashboardSettingsWelcomeRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardDownloadRoute: typeof DashboardDownloadRoute
  DashboardMenuRoute: typeof DashboardMenuRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardTablesRoute: typeof DashboardTablesRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardDownloadRoute: DashboardDownloadRoute,
  DashboardMenuRoute: DashboardMenuRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardTablesRoute: DashboardTablesRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface MobileRouteChildren {
  MobileDailySummaryRoute: typeof MobileDailySummaryRoute
  MobileInventoryRoute: typeof MobileInventoryRoute
  MobileLoginRoute: typeof MobileLoginRoute
  MobileNotificationsRoute: typeof MobileNotificationsRoute
  MobileReportsRoute: typeof MobileReportsRoute
  MobileSettingsRoute: typeof MobileSettingsRoute
  MobileWeeklyReportRoute: typeof MobileWeeklyReportRoute
  MobileIndexRoute: typeof MobileIndexRoute
}

const MobileRouteChildren: MobileRouteChildren = {
  MobileDailySummaryRoute: MobileDailySummaryRoute,
  MobileInventoryRoute: MobileInventoryRoute,
  MobileLoginRoute: MobileLoginRoute,
  MobileNotificationsRoute: MobileNotificationsRoute,
  MobileReportsRoute: MobileReportsRoute,
  MobileSettingsRoute: MobileSettingsRoute,
  MobileWeeklyReportRoute: MobileWeeklyReportRoute,
  MobileIndexRoute: MobileIndexRoute,
}

const MobileRouteWithChildren =
  MobileRoute._addFileChildren(MobileRouteChildren)

interface OpsEmployeesRouteChildren {
  OpsEmployeesEmployeeIdRoute: typeof OpsEmployeesEmployeeIdRoute
  OpsEmployeesIndexRoute: typeof OpsEmployeesIndexRoute
}

const OpsEmployeesRouteChildren: OpsEmployeesRouteChildren = {
  OpsEmployeesEmployeeIdRoute: OpsEmployeesEmployeeIdRoute,
  OpsEmployeesIndexRoute: OpsEmployeesIndexRoute,
}

const OpsEmployeesRouteWithChildren = OpsEmployeesRoute._addFileChildren(
  OpsEmployeesRouteChildren,
)

interface OpsRouteChildren {
  OpsAccountingRoute: typeof OpsAccountingRoute
  OpsComplaintsRoute: typeof OpsComplaintsRoute
  OpsEmployeesRoute: typeof OpsEmployeesRouteWithChildren
  OpsExpensesRoute: typeof OpsExpensesRoute
  OpsInventoryRoute: typeof OpsInventoryRoute
  OpsInventoryCountRoute: typeof OpsInventoryCountRoute
  OpsMenuRoute: typeof OpsMenuRoute
  OpsRecipesRoute: typeof OpsRecipesRoute
  OpsReportArchiveRoute: typeof OpsReportArchiveRoute
  OpsReportsRoute: typeof OpsReportsRoute
  OpsStaffPerformanceRoute: typeof OpsStaffPerformanceRoute
  OpsSuppliersRoute: typeof OpsSuppliersRoute
  OpsWasteRoute: typeof OpsWasteRoute
  OpsIndexRoute: typeof OpsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsAccountingRoute: OpsAccountingRoute,
  OpsComplaintsRoute: OpsComplaintsRoute,
  OpsEmployeesRoute: OpsEmployeesRouteWithChildren,
  OpsExpensesRoute: OpsExpensesRoute,
  OpsInventoryRoute: OpsInventoryRoute,
  OpsInventoryCountRoute: OpsInventoryCountRoute,
  OpsMenuRoute: OpsMenuRoute,
  OpsRecipesRoute: OpsRecipesRoute,
  OpsReportArchiveRoute: OpsReportArchiveRoute,
  OpsReportsRoute: OpsReportsRoute,
  OpsStaffPerformanceRoute: OpsStaffPerformanceRoute,
  OpsSuppliersRoute: OpsSuppliersRoute,
  OpsWasteRoute: OpsWasteRoute,
  OpsIndexRoute: OpsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

interface AccountSettingsRouteChildren {
  AccountSettingsAppearanceRoute: typeof AccountSettingsAppearanceRoute
  AccountSettingsDeliveryRoute: typeof AccountSettingsDeliveryRoute
  AccountSettingsEmployeesRoute: typeof AccountSettingsEmployeesRoute
  AccountSettingsRestaurantRoute: typeof AccountSettingsRestaurantRoute
  AccountSettingsTakeawayRoute: typeof AccountSettingsTakeawayRoute
  AccountSettingsWelcomeRoute: typeof AccountSettingsWelcomeRoute
  AccountSettingsIndexRoute: typeof AccountSettingsIndexRoute
}

const AccountSettingsRouteChildren: AccountSettingsRouteChildren = {
  AccountSettingsAppearanceRoute: AccountSettingsAppearanceRoute,
  AccountSettingsDeliveryRoute: AccountSettingsDeliveryRoute,
  AccountSettingsEmployeesRoute: AccountSettingsEmployeesRoute,
  AccountSettingsRestaurantRoute: AccountSettingsRestaurantRoute,
  AccountSettingsTakeawayRoute: AccountSettingsTakeawayRoute,
  AccountSettingsWelcomeRoute: AccountSettingsWelcomeRoute,
  AccountSettingsIndexRoute: AccountSettingsIndexRoute,
}

const AccountSettingsRouteWithChildren = AccountSettingsRoute._addFileChildren(
  AccountSettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  CashierRoute: CashierRoute,
  CashierLoginRoute: CashierLoginRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DownloadRoute: DownloadRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  KitchenLoginRoute: KitchenLoginRoute,
  KitchenScreenRoute: KitchenScreenRoute,
  LoginRoute: LoginRoute,
  MobileRoute: MobileRouteWithChildren,
  OpsRoute: OpsRouteWithChildren,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  StaffLoginRoute: StaffLoginRoute,
  WaiterLoginRoute: WaiterLoginRoute,
  WaiterScreenRoute: WaiterScreenRoute,
  AccountSettingsRoute: AccountSettingsRouteWithChildren,
  InternalManagersRoute: InternalManagersRoute,
  RTokenRoute: RTokenRoute,
  TTokenRoute: TTokenRoute,
  AccountIndexRoute: AccountIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
