/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CashierRouteImport } from './routes/cashier'
import { Route as CashierLoginRouteImport } from './routes/cashier-login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as KitchenLoginRouteImport } from './routes/kitchen-login'
import { Route as KitchenScreenRouteImport } from './routes/kitchen-screen'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as WaiterLoginRouteImport } from './routes/waiter-login'
import { Route as WaiterScreenRouteImport } from './routes/waiter-screen'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardMenuRouteImport } from './routes/dashboard.menu'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard.reviews'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardTablesRouteImport } from './routes/dashboard.tables'
import { Route as OpsIndexRouteImport } from './routes/ops.index'
import { Route as OpsComplaintsRouteImport } from './routes/ops.complaints'
import { Route as OpsEmployeesRouteImport } from './routes/ops.employees'
import { Route as OpsExpensesRouteImport } from './routes/ops.expenses'
import { Route as OpsInventoryRouteImport } from './routes/ops.inventory'
import { Route as OpsInventoryCountRouteImport } from './routes/ops.inventory-count'
import { Route as OpsRecipesRouteImport } from './routes/ops.recipes'
import { Route as OpsReportsRouteImport } from './routes/ops.reports'
import { Route as OpsStaffPerformanceRouteImport } from './routes/ops.staff-performance'
import { Route as OpsSuppliersRouteImport } from './routes/ops.suppliers'
import { Route as OpsWasteRouteImport } from './routes/ops.waste'
import { Route as OpsEmployeesIndexRouteImport } from './routes/ops.employees.index'
import { Route as OpsEmployeesEmployeeIdRouteImport } from './routes/ops.employees.$employeeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierRoute = CashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierLoginRoute = CashierLoginRouteImport.update({
  id: '/cashier-login',
  path: '/cashier-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenLoginRoute = KitchenLoginRouteImport.update({
  id: '/kitchen-login',
  path: '/kitchen-login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenScreenRoute = KitchenScreenRouteImport.update({
  id: '/kitchen-screen',
  path: '/kitchen-screen',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const WaiterLoginRoute = WaiterLoginRouteImport.update({
  id: '/waiter-login',
  path: '/waiter-login',
  getParentRoute: () => rootRouteImport,
} as any)
const WaiterScreenRoute = WaiterScreenRouteImport.update({
  id: '/waiter-screen',
  path: '/waiter-screen',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMenuRoute = DashboardMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTablesRoute = DashboardTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => DashboardRoute,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsComplaintsRoute = OpsComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => OpsRoute,
} as any)
const OpsEmployeesRoute = OpsEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => OpsRoute,
} as any)
const OpsExpensesRoute = OpsExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => OpsRoute,
} as any)
const OpsInventoryRoute = OpsInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => OpsRoute,
} as any)
const OpsInventoryCountRoute = OpsInventoryCountRouteImport.update({
  id: '/inventory-count',
  path: '/inventory-count',
  getParentRoute: () => OpsRoute,
} as any)
const OpsRecipesRoute = OpsRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => OpsRoute,
} as any)
const OpsReportsRoute = OpsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OpsRoute,
} as any)
const OpsStaffPerformanceRoute = OpsStaffPerformanceRouteImport.update({
  id: '/staff-performance',
  path: '/staff-performance',
  getParentRoute: () => OpsRoute,
} as any)
const OpsSuppliersRoute = OpsSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => OpsRoute,
} as any)
const OpsWasteRoute = OpsWasteRouteImport.update({
  id: '/waste',
  path: '/waste',
  getParentRoute: () => OpsRoute,
} as any)
const OpsEmployeesIndexRoute = OpsEmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsEmployeesRoute,
} as any)
const OpsEmployeesEmployeeIdRoute = OpsEmployeesEmployeeIdRouteImport.update({
  id: '/$employeeId',
  path: '/$employeeId',
  getParentRoute: () => OpsEmployeesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cashier': typeof CashierRoute
  '/cashier-login': typeof CashierLoginRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/kitchen-login': typeof KitchenLoginRoute
  '/kitchen-screen': typeof KitchenScreenRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/waiter-login': typeof WaiterLoginRoute
  '/waiter-screen': typeof WaiterScreenRoute
  '/account/settings': typeof AccountSettingsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tables': typeof DashboardTablesRoute
  '/ops/complaints': typeof OpsComplaintsRoute
  '/ops/employees': typeof OpsEmployeesRouteWithChildren
  '/ops/expenses': typeof OpsExpensesRoute
  '/ops/inventory': typeof OpsInventoryRoute
  '/ops/inventory-count': typeof OpsInventoryCountRoute
  '/ops/recipes': typeof OpsRecipesRoute
  '/ops/reports': typeof OpsReportsRoute
  '/ops/staff-performance': typeof OpsStaffPerformanceRoute
  '/ops/suppliers': typeof OpsSuppliersRoute
  '/ops/waste': typeof OpsWasteRoute
  '/account/': typeof AccountIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/ops/employees/$employeeId': typeof OpsEmployeesEmployeeIdRoute
  '/ops/employees/': typeof OpsEmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cashier': typeof CashierRoute
  '/cashier-login': typeof CashierLoginRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/kitchen-login': typeof KitchenLoginRoute
  '/kitchen-screen': typeof KitchenScreenRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/waiter-login': typeof WaiterLoginRoute
  '/waiter-screen': typeof WaiterScreenRoute
  '/account/settings': typeof AccountSettingsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tables': typeof DashboardTablesRoute
  '/ops/complaints': typeof OpsComplaintsRoute
  '/ops/expenses': typeof OpsExpensesRoute
  '/ops/inventory': typeof OpsInventoryRoute
  '/ops/inventory-count': typeof OpsInventoryCountRoute
  '/ops/recipes': typeof OpsRecipesRoute
  '/ops/reports': typeof OpsReportsRoute
  '/ops/staff-performance': typeof OpsStaffPerformanceRoute
  '/ops/suppliers': typeof OpsSuppliersRoute
  '/ops/waste': typeof OpsWasteRoute
  '/account': typeof AccountIndexRoute
  '/ops': typeof OpsIndexRoute
  '/ops/employees/$employeeId': typeof OpsEmployeesEmployeeIdRoute
  '/ops/employees': typeof OpsEmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cashier': typeof CashierRoute
  '/cashier-login': typeof CashierLoginRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/kitchen-login': typeof KitchenLoginRoute
  '/kitchen-screen': typeof KitchenScreenRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/waiter-login': typeof WaiterLoginRoute
  '/waiter-screen': typeof WaiterScreenRoute
  '/account/settings': typeof AccountSettingsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tables': typeof DashboardTablesRoute
  '/ops/complaints': typeof OpsComplaintsRoute
  '/ops/employees': typeof OpsEmployeesRouteWithChildren
  '/ops/expenses': typeof OpsExpensesRoute
  '/ops/inventory': typeof OpsInventoryRoute
  '/ops/inventory-count': typeof OpsInventoryCountRoute
  '/ops/recipes': typeof OpsRecipesRoute
  '/ops/reports': typeof OpsReportsRoute
  '/ops/staff-performance': typeof OpsStaffPerformanceRoute
  '/ops/suppliers': typeof OpsSuppliersRoute
  '/ops/waste': typeof OpsWasteRoute
  '/account/': typeof AccountIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/ops/employees/$employeeId': typeof OpsEmployeesEmployeeIdRoute
  '/ops/employees/': typeof OpsEmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cashier'
    | '/cashier-login'
    | '/dashboard'
    | '/forgot-password'
    | '/kitchen-login'
    | '/kitchen-screen'
    | '/login'
    | '/ops'
    | '/setup'
    | '/signup'
    | '/waiter-login'
    | '/waiter-screen'
    | '/account/settings'
    | '/dashboard/analytics'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/tables'
    | '/ops/complaints'
    | '/ops/employees'
    | '/ops/expenses'
    | '/ops/inventory'
    | '/ops/inventory-count'
    | '/ops/recipes'
    | '/ops/reports'
    | '/ops/staff-performance'
    | '/ops/suppliers'
    | '/ops/waste'
    | '/account/'
    | '/ops/'
    | '/ops/employees/$employeeId'
    | '/ops/employees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cashier'
    | '/cashier-login'
    | '/dashboard'
    | '/forgot-password'
    | '/kitchen-login'
    | '/kitchen-screen'
    | '/login'
    | '/setup'
    | '/signup'
    | '/waiter-login'
    | '/waiter-screen'
    | '/account/settings'
    | '/dashboard/analytics'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/tables'
    | '/ops/complaints'
    | '/ops/expenses'
    | '/ops/inventory'
    | '/ops/inventory-count'
    | '/ops/recipes'
    | '/ops/reports'
    | '/ops/staff-performance'
    | '/ops/suppliers'
    | '/ops/waste'
    | '/account'
    | '/ops'
    | '/ops/employees/$employeeId'
    | '/ops/employees'
  id:
    | '__root__'
    | '/'
    | '/cashier'
    | '/cashier-login'
    | '/dashboard'
    | '/forgot-password'
    | '/kitchen-login'
    | '/kitchen-screen'
    | '/login'
    | '/ops'
    | '/setup'
    | '/signup'
    | '/waiter-login'
    | '/waiter-screen'
    | '/account/settings'
    | '/dashboard/analytics'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/tables'
    | '/ops/complaints'
    | '/ops/employees'
    | '/ops/expenses'
    | '/ops/inventory'
    | '/ops/inventory-count'
    | '/ops/recipes'
    | '/ops/reports'
    | '/ops/staff-performance'
    | '/ops/suppliers'
    | '/ops/waste'
    | '/account/'
    | '/ops/'
    | '/ops/employees/$employeeId'
    | '/ops/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CashierRoute: typeof CashierRoute
  CashierLoginRoute: typeof CashierLoginRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  KitchenLoginRoute: typeof KitchenLoginRoute
  KitchenScreenRoute: typeof KitchenScreenRoute
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRouteWithChildren
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  WaiterLoginRoute: typeof WaiterLoginRoute
  WaiterScreenRoute: typeof WaiterScreenRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashier': {
      id: '/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof CashierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashier-login': {
      id: '/cashier-login'
      path: '/cashier-login'
      fullPath: '/cashier-login'
      preLoaderRoute: typeof CashierLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-login': {
      id: '/kitchen-login'
      path: '/kitchen-login'
      fullPath: '/kitchen-login'
      preLoaderRoute: typeof KitchenLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-screen': {
      id: '/kitchen-screen'
      path: '/kitchen-screen'
      fullPath: '/kitchen-screen'
      preLoaderRoute: typeof KitchenScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiter-login': {
      id: '/waiter-login'
      path: '/waiter-login'
      fullPath: '/waiter-login'
      preLoaderRoute: typeof WaiterLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiter-screen': {
      id: '/waiter-screen'
      path: '/waiter-screen'
      fullPath: '/waiter-screen'
      preLoaderRoute: typeof WaiterScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/menu': {
      id: '/dashboard/menu'
      path: '/menu'
      fullPath: '/dashboard/menu'
      preLoaderRoute: typeof DashboardMenuRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tables': {
      id: '/dashboard/tables'
      path: '/tables'
      fullPath: '/dashboard/tables'
      preLoaderRoute: typeof DashboardTablesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/complaints': {
      id: '/ops/complaints'
      path: '/complaints'
      fullPath: '/ops/complaints'
      preLoaderRoute: typeof OpsComplaintsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/employees': {
      id: '/ops/employees'
      path: '/employees'
      fullPath: '/ops/employees'
      preLoaderRoute: typeof OpsEmployeesRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/expenses': {
      id: '/ops/expenses'
      path: '/expenses'
      fullPath: '/ops/expenses'
      preLoaderRoute: typeof OpsExpensesRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/inventory': {
      id: '/ops/inventory'
      path: '/inventory'
      fullPath: '/ops/inventory'
      preLoaderRoute: typeof OpsInventoryRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/inventory-count': {
      id: '/ops/inventory-count'
      path: '/inventory-count'
      fullPath: '/ops/inventory-count'
      preLoaderRoute: typeof OpsInventoryCountRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/recipes': {
      id: '/ops/recipes'
      path: '/recipes'
      fullPath: '/ops/recipes'
      preLoaderRoute: typeof OpsRecipesRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/reports': {
      id: '/ops/reports'
      path: '/reports'
      fullPath: '/ops/reports'
      preLoaderRoute: typeof OpsReportsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/staff-performance': {
      id: '/ops/staff-performance'
      path: '/staff-performance'
      fullPath: '/ops/staff-performance'
      preLoaderRoute: typeof OpsStaffPerformanceRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/suppliers': {
      id: '/ops/suppliers'
      path: '/suppliers'
      fullPath: '/ops/suppliers'
      preLoaderRoute: typeof OpsSuppliersRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/waste': {
      id: '/ops/waste'
      path: '/waste'
      fullPath: '/ops/waste'
      preLoaderRoute: typeof OpsWasteRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/employees/': {
      id: '/ops/employees/'
      path: '/'
      fullPath: '/ops/employees/'
      preLoaderRoute: typeof OpsEmployeesIndexRouteImport
      parentRoute: typeof OpsEmployeesRoute
    }
    '/ops/employees/$employeeId': {
      id: '/ops/employees/$employeeId'
      path: '/$employeeId'
      fullPath: '/ops/employees/$employeeId'
      preLoaderRoute: typeof OpsEmployeesEmployeeIdRouteImport
      parentRoute: typeof OpsEmployeesRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardMenuRoute: typeof DashboardMenuRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTablesRoute: typeof DashboardTablesRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardMenuRoute: DashboardMenuRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTablesRoute: DashboardTablesRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface OpsEmployeesRouteChildren {
  OpsEmployeesEmployeeIdRoute: typeof OpsEmployeesEmployeeIdRoute
  OpsEmployeesIndexRoute: typeof OpsEmployeesIndexRoute
}

const OpsEmployeesRouteChildren: OpsEmployeesRouteChildren = {
  OpsEmployeesEmployeeIdRoute: OpsEmployeesEmployeeIdRoute,
  OpsEmployeesIndexRoute: OpsEmployeesIndexRoute,
}

const OpsEmployeesRouteWithChildren = OpsEmployeesRoute._addFileChildren(
  OpsEmployeesRouteChildren,
)

interface OpsRouteChildren {
  OpsComplaintsRoute: typeof OpsComplaintsRoute
  OpsEmployeesRoute: typeof OpsEmployeesRouteWithChildren
  OpsExpensesRoute: typeof OpsExpensesRoute
  OpsInventoryRoute: typeof OpsInventoryRoute
  OpsInventoryCountRoute: typeof OpsInventoryCountRoute
  OpsRecipesRoute: typeof OpsRecipesRoute
  OpsReportsRoute: typeof OpsReportsRoute
  OpsStaffPerformanceRoute: typeof OpsStaffPerformanceRoute
  OpsSuppliersRoute: typeof OpsSuppliersRoute
  OpsWasteRoute: typeof OpsWasteRoute
  OpsIndexRoute: typeof OpsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsComplaintsRoute: OpsComplaintsRoute,
  OpsEmployeesRoute: OpsEmployeesRouteWithChildren,
  OpsExpensesRoute: OpsExpensesRoute,
  OpsInventoryRoute: OpsInventoryRoute,
  OpsInventoryCountRoute: OpsInventoryCountRoute,
  OpsRecipesRoute: OpsRecipesRoute,
  OpsReportsRoute: OpsReportsRoute,
  OpsStaffPerformanceRoute: OpsStaffPerformanceRoute,
  OpsSuppliersRoute: OpsSuppliersRoute,
  OpsWasteRoute: OpsWasteRoute,
  OpsIndexRoute: OpsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CashierRoute: CashierRoute,
  CashierLoginRoute: CashierLoginRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  KitchenLoginRoute: KitchenLoginRoute,
  KitchenScreenRoute: KitchenScreenRoute,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRouteWithChildren,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  WaiterLoginRoute: WaiterLoginRoute,
  WaiterScreenRoute: WaiterScreenRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountIndexRoute: AccountIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
